/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estructura.de.datos;

import estructura.de.datos.ListaDoble.ListaDoble;
import estructura.de.datos.ListaDoble.NodoDatoLD;
import estructura.de.datos.Pila.NodoDatoPila;
import estructura.de.datos.Pila.Pila;

/**
 *
 * @author Vale
 */
public class GUI extends javax.swing.JFrame {

    private ListaDoble Ares_LD = new ListaDoble();
    private Pila Ares_Pila = new Pila();
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    
    private void actualizar_matriz_pila()
    {
        try{
            String[] datos = Ares_Pila.mostrar().split(",");
            String matriz[][] = new String[datos.length][3];
        
        for (int i = 0; i < matriz.length; i++) {
            matriz[i][0] = datos[i].split("-")[0];
            matriz[i][1] = datos[i].split("-")[1];
            matriz[i][2] = datos[i].split("-")[2];

        }
        
        tabla_pila.setModel(
                new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Nombre de la canción:", "Nombre del cantante:", "Año de lanzamiento:"
                }
        ));
        jScrollPane2.setViewportView(tabla_pila);
        }catch(NullPointerException e){
            String[][] matriz = new String[0][0]; 
            tabla_pila.setModel(
                new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Nombre de la canción:", "Nombre del cantante:", "Año de lanzamiento:"
                }
        ));
        }
        
        
        
    }
    
    
    private void actualizar_matriz_LD()
    {
        try{
            String[] datos = Ares_LD.toString().split(",");
            String matriz[][] = new String[datos.length][3];
        
        for (int i = 0; i < matriz.length; i++) {
            matriz[i][0] = datos[i].split("-")[0];
            matriz[i][1] = datos[i].split("-")[1];
            matriz[i][2] = datos[i].split("-")[2];

        }
        
        tabla_LD.setModel(
                new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Nombre de la canción:", "Nombre del cantante:", "Año de lanzamiento:"
                }
        ));
        jScrollPane3.setViewportView(tabla_LD);
        }catch(NullPointerException e){
            String[][] matriz = new String[0][0]; 
            tabla_LD.setModel(
                new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Nombre de la canción:", "Nombre del cantante:", "Año de lanzamiento:"
                }
        ));
        }
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Agregar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Mover = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Nombre_artista = new javax.swing.JLabel();
        anno = new javax.swing.JLabel();
        Buscar_cancion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1Nombre_cancion = new javax.swing.JTextField();
        jTextFieldNombre_artista = new javax.swing.JTextField();
        jTextFieldAnnocancion = new javax.swing.JTextField();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_pila = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_LD = new javax.swing.JTable();
        Nombre_artista1 = new javax.swing.JLabel();
        Nombre_artista2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Agregar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Eliminar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Mover.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        Mover.setText("Mover");
        Mover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoverActionPerformed(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Nombre_artista.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Nombre_artista.setText("Nombre del artista:");

        anno.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        anno.setText("Año de la cancion:");

        Buscar_cancion.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Buscar_cancion.setText("Buscar cancion:");

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ares.png"))); // NOI18N
        jLabel2.setText("Ares");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextField1Nombre_cancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1Nombre_cancionActionPerformed(evt);
            }
        });

        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("Nombre de la cancion:");

        tabla_pila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_pila);

        tabla_LD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabla_LD);

        Nombre_artista1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Nombre_artista1.setText("Lista");

        Nombre_artista2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Nombre_artista2.setText("Pila");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mover, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Nombre_artista1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Nombre_artista2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Buscar_cancion)
                                    .addGap(231, 310, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(Nombre_artista)
                                        .addComponent(anno))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldNombre_artista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jTextFieldAnnocancion, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1Nombre_cancion))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1Nombre_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_artista)
                    .addComponent(jTextFieldNombre_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAnnocancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar)
                    .addComponent(Eliminar)
                    .addComponent(Mover))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar_cancion)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buscar)
                .addGap(18, 18, 18)
                .addComponent(Nombre_artista2)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(Nombre_artista1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        String nombre_cancion = jTextField1Nombre_cancion.getText();
        String nombre_artista = jTextFieldNombre_artista.getText();
        int anno = Integer.parseInt(jTextFieldAnnocancion.getText());
        
        NodoDatoPila nuevoNodoDato = new NodoDatoPila(new Dato(nombre_cancion, nombre_artista, anno));
        
        Ares_Pila.push(nuevoNodoDato);
        
        actualizar_matriz_pila();
        
    }//GEN-LAST:event_AgregarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        
        Ares_Pila.pop();
        actualizar_matriz_pila();
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void jTextField1Nombre_cancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1Nombre_cancionActionPerformed

    }//GEN-LAST:event_jTextField1Nombre_cancionActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void MoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoverActionPerformed
        
        Ares_LD.agregar_recursivo(Ares_Pila);
        actualizar_matriz_pila();
        actualizar_matriz_LD();
    }//GEN-LAST:event_MoverActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        
        Dato dato_encontrado = Ares_LD.buscar(jTextFieldBuscar.getText());
        
        
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Buscar_cancion;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Mover;
    private javax.swing.JLabel Nombre_artista;
    private javax.swing.JLabel Nombre_artista1;
    private javax.swing.JLabel Nombre_artista2;
    private javax.swing.JLabel anno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1Nombre_cancion;
    private javax.swing.JTextField jTextFieldAnnocancion;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldNombre_artista;
    private javax.swing.JTable tabla_LD;
    private javax.swing.JTable tabla_pila;
    // End of variables declaration//GEN-END:variables

    
}
